name = "Pixie"
uuid = "66699cd8-9c01-4e9d-a059-b96c86d16b3a"
authors = ["erik.faulhaber <44124897+efaulhaber@users.noreply.github.com>"]
version = "0.1.0"

[deps]
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
